#!/usr/bin/env python
# coding: utf-8

from itertools import compress

MPS = {'Aki-Matilda Høegh-Dam': 'Aki-Matilda Høegh-Dam',
       'Alex Ahrendtsen': 'Alex Ahrendtsen',
       'Alex Vanopslagh': 'Alex Vanopslagh',
       'Anders Kronborg': 'Anders Kronborg',
       'Andreas Steenberg': 'Andreas Steenberg',
       'Ane Halsboe-Jørgensen': 'Ane Halsboe-Jørgensen',
       'Anne Honoré Østergaard': 'Anne Honoré Østergaard',
       'Anne Østergaard': 'Anne Honoré Østergaard',
       'Anne Honoré': 'Anne Honoré Østergaard',
       'Anne Paulin': 'Anne Paulin',
       'Anne Sophie Callesen': 'Anne Sophie Callesen',
       'Anne Callesen': 'Anne Sophie Callesen',
       'Anne Valentina Berthelsen': 'Anne Valentina Berthelsen',
       'Anne Berthelsen': 'Anne Valentina Berthelsen',
       'Anne Rasmussen': 'Anne Rasmussen',
       'Anne Valentina': 'Anne Valentina Berthelsen',
       'Annette Lind': 'Annette Lind',
       'Anni Matthiesen': 'Anni Matthiesen',
       'Astrid Carøe': 'Astrid Carøe',
       'Astrid Krag': 'Astrid Krag',
       'Benny Engelbrecht': 'Benny Engelbrecht',
       'Bent Bøgsted': 'Bent Bøgsted',
       'Bertel Haarder': 'Bertel Haarder',
       'Birgitte Bergman': 'Birgitte Bergman',
       'Birgitte Vind': 'Birgitte Vind',
       'Bjarne Laustsen': 'Bjarne Laustsen',
       'Bjørn Brandenborg': 'Bjørn Brandenborg',
       'Brigitte Klintskov Jerkel': 'Brigitte Klintskov Jerkel',
       'Brigitte Jerkel': 'Brigitte Klintskov Jerkel',
       'Brigitte Klintskov': 'Brigitte Klintskov Jerkel',
       'Britt Bager': 'Britt Bager',
       'Bruno Jerup': 'Bruno Jerup',
       'Camilla Fabricius': 'Camilla Fabricius',
       'Carl Valentin': 'Carl Valentin',
       'Carsten Kissmeyer': 'Carsten Kissmeyer',
       'Charlotte Broman Mølbæk': 'Charlotte Broman Mølbæk',
       'Charlotte Mølbæk': 'Charlotte Broman Mølbæk',
       'Charlotte Broman': 'Charlotte Broman Mølbæk',
       'Christian Juhl': 'Christian Juhl',
       'Christian Rabjerg Madsen': 'Christian Rabjerg Madsen',
       'Christian Madsen': 'Christian Rabjerg Madsen',
       'Christian Rabjerg': 'Christian Rabjerg Madsen',
       'Christina Thorholm': 'Christina Thorholm',
       'Christoffer Aagaard Melson': 'Christoffer Aagaard Melson',
       'Christoffer Melson': 'Christoffer Aagaard Melson',
       'Christoffer Aagaard': 'Christoffer Aagaard Melson',
       'Claus Hjort Frederiksen': 'Claus Hjort Frederiksen',
       'Claus Frederiksen': 'Claus Hjort Frederiksen',
       'Claus Hjort': 'Claus Hjort Frederiksen',
       'Dan Jørgensen': 'Dan Jørgensen',
       'Daniel Toft Jakobsen': 'Daniel Toft Jakobsen',
       'Daniel Jakobsen': 'Daniel Toft Jakobsen',
       'Daniel Toft': 'Daniel Toft Jakobsen',
       'Dennis Flydtkjær': 'Dennis Flydtkjær',
       'Edmund Joensen': 'Edmund Joensen',
       'Egil Hulgaard': 'Egil Hulgaard',
       'Ellen Trane Nørby': 'Ellen Trane Nørby',
       'Ellen Nørby': 'Ellen Trane Nørby',
       'Ellen Trane': 'Ellen Trane Nørby',
       'Erling Bonnesen': 'Erling Bonnesen',
       'Eva Flyvholm': 'Eva Flyvholm',
       'Eva Kjer Hansen': 'Eva Kjer Hansen',
       'Eva Hansen': 'Eva Kjer Hansen',
       'Eva Kjer': 'Eva Kjer Hansen',
       'Fatma Øktem': 'Fatma Øktem',
       'Flemming Møller Mortensen': 'Flemming Møller Mortensen',
       'Flemming Mortensen': 'Flemming Møller Mortensen',
       'Flemming Møller': 'Flemming Møller Mortensen',
       'Gitte Willumsen': 'Gitte Willumsen',
       'Halime Oguz': 'Halime Oguz',
       'Hans Andersen': 'Hans Andersen',
       'Hans Christian Schmidt': 'Hans Christian Schmidt',
       'Hans Schmidt': 'Hans Christian Schmidt',
       'Hans Kristian Skibby': 'Hans Kristian Skibby',
       'Hans Skibby': 'Hans Kristian Skibby',
       'Heidi Bank': 'Heidi Bank',
       'Henning Hyllested': 'Henning Hyllested',
       'Henrik Dahl': 'Henrik Dahl',
       'Henrik Møller': 'Henrik Møller',
       'Henrik Vinther': 'Henrik Vinther',
       'Henrik Dam Kristensen': 'Henrik Dam Kristensen',
       'Henrik Dam': 'Henrik Dam Kristensen',
       'Henrik Kristensen': 'Henrik Dam Kristensen',
       'Ida Auken': 'Ida Auken',
       'Ina Strøjer-Schmidt': 'Ina Strøjer-Schmidt',
       'Jacob Jensen': 'Jacob Jensen',
       'Jacob Mark': 'Jacob Mark',
       'Jakob Ellemann-Jensen': 'Jakob Ellemann-Jensen',
       'Jakob Sølvhøj': 'Jakob Sølvhøj',
       'Jan Johansen': 'Jan Johansen',
       'Jan E. Jørgensen': 'Jan E. Jørgensen',
       'Jan Jørgensen': 'Jan E. Jørgensen',
       'Jane Heitmann': 'Jane Heitmann',
       'Jens Joel': 'Jens Joel',
       'Jens Rohde': 'Jens Rohde',
       'Jens Henrik Thulesen Dahl': 'Jens Henrik Thulesen Dahl',
       'Jens Henrik Dahl': 'Jens Henrik Thulesen Dahl',
       'Jens Henrik Thulesen': 'Jens Henrik Thulesen Dahl',
       'Jeppe Bruus': 'Jeppe Bruus',
       'Jesper Petersen': 'Jesper Petersen',
       'Jette Gottlieb': 'Jette Gottlieb',
       'Julie Skovsby': 'Julie Skovsby',
       'Karen Ellemann': 'Karen Ellemann',
       'Karina Adsbøl': 'Karina Adsbøl',
       'Karina Lorentzen Dehnhardt': 'Karina Lorentzen Dehnhardt',
       'Karina Lorentzen': 'Karina Lorentzen Dehnhardt',
       'Karina Dehnhardt': 'Karina Dehnhardt',
       'Karsten Hønge': 'Karsten Hønge',
       'Kasper Roug': 'Kasper Roug',
       'Kasper Sand Kjær': 'Kasper Sand Kjær',
       'Kasper Sand': 'Kasper Sand Kjær',
       'Kasper Kjær': 'Kasper Sand Kjær',
       'Katarina Ammitzbøll': 'Katarina Ammitzbøll',
       'Kathrine Olldag': 'Kathrine Olldag',
       'Katrine Robsøe': 'Katrine Robsøe',
       'Kenneth Mikkelsen': 'Kenneth Mikkelsen',
       'Kim Valentin': 'Kim Valentin',
       'Kirsten Normann Andersen': 'Kirsten Normann Andersen',
       'Kirsten Normann': 'Kirsten Normann Andersen',
       'Kirsten Andersen': 'Kirsten Normann Andersen',
       'Kristian Pihl Lorentzen': 'Kristian Pihl Lorentzen',
       'Kristian Pihl': 'Kristian Pihl Lorentzen',
       'Kristian Lorentzen': 'Kristian Pihl Lorentzen',
       #'Kristian Thulesen Dahl': 'Kristian Thulesen Dahl',
       #'Kristian Thulesen': 'Kristian Thulesen Dahl',
       #'Kristian Dahl': 'Kristian Thulesen Dahl',
       'Kaare Dybvad Bek': 'Kaare Dybvad Bek',
       'Kaare Dybvad': 'Kaare Dybvad Bek',
       'Kaare Bek': 'Kaare Dybvad Bek',
       'Lars Aslan Rasmussen': 'Lars Aslan Rasmussen',
       'Lars Aslan': 'Lars Aslan Rasmussen',
       'Lars Rasmussen': 'Lars Aslan Rasmussen',
       'Lars Boje Mathiesen': 'Lars Boje Mathiesen',
       'Lars Boje': 'Lars Boje Mathiesen',
       'Lars Mathiesen': 'Lars Boje Mathiesen',
       'Lars Christian Lilleholt': 'Lars Christian Lilleholt',
       'Lars Christian': 'Lars Christian Lilleholt',
       'Lars Lilleholt': 'Lars Christian Lilleholt',
       'Lars Løkke Rasmussen': 'Lars Løkke Rasmussen',
       'Lars Løkke': 'Lars Løkke Rasmussen',
       'Lea Wermelin': 'Lea Wermelin',
       'Leif Lahn Jensen': 'Leif Lahn Jensen',
       'Leif Lahn': 'Leif Lahn Jensen',
       'Leif Jensen': 'Leif Lahn Jensen',
       'Lennart Damsbo-Andersen': 'Lennart Damsbo-Andersen',
       'Lisbeth Bech-Nielsen': 'Lisbeth Bech-Nielsen',
       'Lise Bech': 'Lise Bech',
       'Liselott Blixt': 'Liselott Blixt',
       'Lotte Rod': 'Lotte Rod',
       'Louise Schack Elholm': 'Louise Schack Elholm',
       'Louise Schack': 'Louise Schack Elholm',
       'Louise Elholm': 'Louise Schack Elholm',
       'Mads Fuglede': 'Mads Fuglede',
       'Magnus Heunicke': 'Magnus Heunicke',
       'Mai Mercado': 'Mai Mercado',
       'Mai Villadsen': 'Mai Villadsen',
       'Maja Torp': 'Maja Torp',
       'Malte Larsen': 'Malte Larsen',
       'Marcus Knuth': 'Marcus Knuth',
       'Marianne Jelved': 'Marianne Jelved',
       'Marie Bjerre': 'Marie Bjerre',
       'Marie Krarup': 'Marie Krarup',
       'Marlene Ambo-Rasmussen': 'Marlene Ambo-Rasmussen',
       'Martin Geertsen': 'Martin Geertsen',
       'Martin Lidegaard': 'Martin Lidegaard',
       'Mattias Tesfaye': 'Mattias Tesfaye',
       'Merete Scheelsbeck': 'Merete Scheelsbeck',
       'Mette Abildgaard': 'Mette Abildgaard',
       'Mette Frederiksen': 'Mette Frederiksen',
       'Mette Gjerskov': 'Mette Gjerskov',
       'Mette Thiesen': 'Mette Thiesen',
       'Mette Hjermind Dencker': 'Mette Hjermind Dencker',
       'Mette Hjermind': 'Mette Hjermind Dencker',
       'Mette Dencker': 'Mette Hjermind Dencker',
       'Michael Aastrup Jensen': 'Michael Aastrup Jensen',
       'Michael Aastrup': 'Michael Aastrup Jensen',
       'Michael Jensen': 'Michael Aastrup Jensen',
       'Mogens Jensen': 'Mogens Jensen',
       'Mona Juul': 'Mona Juul',
       'Morten Bødskov': 'Morten Bødskov',
       'Morten Dahlin': 'Morten Dahlin',
       'Morten Messerschmidt': 'Morten Messerschmidt',
       'Naser Khader': 'Naser Khader',
       'Nicolai Wammen': 'Nicolai Wammen',
       'Niels Flemming Hansen': 'Niels Flemming Hansen',
       'Niels Flemming': 'Niels Flemming Hansen',
       'Niels Hansen': 'Niels Flemming Hansen',
       'Ole Birk Olesen': 'Ole Birk Olesen',
       'Ole Birk': 'Ole Birk Olesen',
       'Orla Hav': 'Orla Hav',
       'Orla Østerby': 'Orla Østerby',
       'Peder Hvelplund': 'Peder Hvelplund',
       'Per Larsen': 'Per Larsen',
       'Pernille Rosenkrantz-Theil': 'Pernille Rosenkrantz-Theil',
       'Pernille Skipper': 'Pernille Skipper',
       'Pernille Vermund': 'Pernille Vermund',
       'Peter Hummelgaard': 'Peter Hummelgaard',
       'Peter Juel-Jensen': 'Peter Juel-Jensen',
       'Peter Seier Christensen': 'Peter Seier Christensen',
       'Peter Christensen': 'Peter Seier Christensen',
       'Peter Seier': 'Peter Seier Christensen',
       'Peter Skaarup': 'Peter Skaarup',
       'Pia Kjærsgaard': 'Pia Kjærsgaard',
       'Pia Olsen Dyhr': 'Pia Olsen Dyhr',
       'Pia Olsen': 'Pia Olsen Dyhr',
       'Pia Dyhr': 'Pia Olsen Dyhr',
       'Preben Bang Henriksen': 'Preben Bang Henriksen',
       'Preben Bang': 'Preben Bang Henriksen',
       'Preben Henriksen': 'Preben Bang Henriksen',
       'Rasmus Jarlov': 'Rasmus Jarlov',
       'Rasmus Nordqvist': 'Rasmus Nordqvist',
       'Rasmus Prehn': 'Rasmus Prehn',
       'Rasmus Stoklund': 'Rasmus Stoklund',
       'Rasmus Vestergaard': 'Rasmus Vestergaard',
       'Rasmus Helveg Petersen': 'Rasmus Helveg Petersen',
       'Rasmus Helveg': 'Rasmus Helveg Petersen',
       'Rasmus Petersen': 'Rasmus Helveg Petersen',
       'Rasmus Horn Langhoff': 'Rasmus Horn Langhoff',
       'Rasmus Horn': 'Rasmus Horn Langhoff',
       'Rasmus Langhoff': 'Rasmus Horn Langhoff',
       'René Christensen': 'René Christensen',
       'Rosa Lund': 'Rosa Lund',
       'Rune Lund': 'Rune Lund',
       'Samira Nawa': 'Samira Nawa',
       'Signe Munk': 'Signe Munk',
       'Sikandar Siddique': 'Sikandar Siddique',
       'Simon Kollerup': 'Simon Kollerup',
       'Simon Emil Ammitzbøll-Bille': 'Simon Emil Ammitzbøll-Bille',
       'Simon Ammitzbøll-Bille': 'Simon Emil Ammitzbøll-Bille',
       'Sjúrður Skaale': 'Sjúrður Skaale',
       'Sofie Carsten Nielsen': 'Sofie Carsten Nielsen',
       'Sofie Carsten': 'Sofie Carsten Nielsen',
       'Sofie Nielsen': 'Sofie Carsten Nielsen',
       'Sophie Løhde': 'Sophie Løhde',
       'Stén Knuth': 'Stén Knuth',
       'Sten Knuth': 'Stén Knuth',
       'Stinus Lindgreen': 'Stinus Lindgreen',
       'Susan Kronborg': 'Susan Kronborg',
       'Susanne Zimmer': 'Susanne Zimmer',
       'Susanne Eilersen': 'Susanne Eilersen',
       'Søren Espersen': 'Søren Espersen',
       'Søren Søndergaard': 'Søren Søndergaard',
       'Søren Egge Rasmussen': 'Søren Egge Rasmussen',
       'Søren Egge': 'Søren Egge Rasmussen',
       'Søren Rasmussen': 'Søren Egge Rasmussen',
       'Søren Pape Poulsen': 'Søren Pape Poulsen',
       'Søren Pape': 'Søren Pape Poulsen',
       'Søren Poulsen': 'Søren Pape Poulsen',
       'Tanja Larsson': 'Tanja Larsson',
       'Theresa Berg Andersen': 'Theresa Berg Andersen',
       'Theresa Berg': 'Theresa Berg Andersen',
       'Theresa Andersen': 'Theresa Berg Andersen',
       'Thomas Danielsen': 'Thomas Danielsen',
       'Thomas Jensen': 'Thomas Jensen',
       'Torsten Gejl': 'Torsten Gejl',
       'Torsten Schack Pedersen': 'Torsten Schack Pedersen',
       'Torsten Schack': 'Torsten Schack Pedersen',
       'Torsten Pedersen': 'Torsten Schack Pedersen',
       'Trine Bramsen': 'Trine Bramsen',
       'Trine Torp': 'Trine Torp',
       'Troels Ravn': 'Troels Ravn',
       'Troels Lund Poulsen': 'Troels Lund Poulsen',
       'Troels Lund': 'Troels Lund Poulsen',
       'Troels Poulsen': 'Troels Lund Poulsen',
       'Uffe Elbæk': 'Uffe Elbæk',
       'Ulla Tørnæs': 'Ulla Tørnæs',
       'Victoria Velasquez': 'Victoria Velasquez',
       'Zenia Stampe': 'Zenia Stampe',
       'Aaja Chemnitz Larsen': 'Aaja Chemnitz Larsen',
       'Aaja Chemnitz': 'Aaja Chemnitz Larsen',
       'Aaja Larsen': 'Aaja Chemnitz Larsen'}

def mp_check(text, mps = MPS):
    '''
    Checks MP mentions in article.
    '''
    
    if any(mp in text for mp in mps.keys()):
        name_matches = list(compress(mps, [mp in text for mp in mps.keys()]))
    else:
        name_matches = []
    
    name_matches_checked = []
    for name_match in name_matches:
        for synonym, name in mps.items():
            if synonym in name_match:
                name_match = name_match.replace(synonym, name)
                break
        name_matches_checked.append(name_match)
    
    name_matches_checked = list(set(name_matches_checked))
    
    return(name_matches_checked)