from itertools import compress

MPS = ['Aki-Matilda Høegh-Dam',
       'Alex Ahrendtsen',
       'Alex Vanopslagh',
       'Anders Kronborg',
       'Andreas Steenberg',
       'Ane Halsboe-Jørgensen',
       'Anne Honoré Østergaard',
       'Anne Østergaard',
       'Anne Honoré'
       'Anne Paulin',
       'Anne Sophie Callesen',
       'Anne Callesen',
       'Anne Valentina Berthelsen',
       'Anne Berthelsen',
       'Anne Valentina',
       'Annette Lind',
       'Anni Matthiesen',
       'Astrid Carøe',
       'Astrid Krag',
       'Benny Engelbrecht',
       'Bent Bøgsted',
       'Bertel Haarder',
       'Birgitte Bergman',
       'Birgitte Vind',
       'Bjarne Laustsen',
       'Bjørn Brandenborg',
       'Brigitte Klintskov Jerkel',
       'Brigitte Jerkel',
       'Brigitte Klintskov',
       'Britt Bager',
       'Bruno Jerup',
       'Camilla Fabricius',
       'Carl Valentin',
       'Carsten Kissmeyer',
       'Charlotte Broman Mølbæk',
       'Charlotte Mølbæk',
       'Charlotte Broman',
       'Christian Juhl',
       'Christian Rabjerg Madsen',
       'Christian Madsen',
       'Christian Rabjerg',
       'Christoffer Aagaard Melson',
       'Christoffer Melson',
       'Christoffer Aagaard',
       'Claus Hjort Frederiksen',
       'Claus Frederiksen',
       'Claus Hjort',
       'Dan Jørgensen',
       'Daniel Toft Jakobsen',
       'Daniel Jakobsen',
       'Daniel Toft',
       'Dennis Flydtkjær',
       'Edmund Joensen',
       'Egil Hulgaard',
       'Ellen Trane Nørby',
       'Ellen Nørby',
       'Ellen Trane',
       'Erling Bonnesen',
       'Eva Flyvholm',
       'Eva Kjer Hansen',
       'Eva Hansen',
       'Eva Kjer',
       'Fatma Øktem',
       'Flemming Møller Mortensen',
       'Flemming Mortensen',
       'Flemming Møller',
       'Halime Oguz',
       'Hans Andersen',
       'Hans Christian Schmidt',
       'Hans Kristian Skibby',
       'Heidi Bank',
       'Henning Hyllested',
       'Henrik Dahl',
       'Henrik Møller',
       'Henrik  Vinther',
       'Henrik Dam Kristensen',
       'Henrik Dam',
       'Henrik Kristensen',
       'Ida Auken',
       'Ina Strøjer-Schmidt',
       'Inger Støjberg',
       'Jacob Jensen',
       'Jacob Mark',
       'Jakob Ellemann-Jensen',
       'Jakob Sølvhøj',
       'Jan Johansen',
       'Jan E. Jørgensen',
       'Jan Jørgensen',
       'Jane Heitmann',
       'Jens Joel',
       'Jens Rohde',
       'Jens Henrik Thulesen Dahl',
       'Jens Henrik Dahl',
       'Jens Henrik Thulesen',
       'Jeppe Bruus',
       'Jesper Petersen',
       'Jette Gottlieb',
       'Julie Skovsby',
       'Karen Ellemann',
       'Karina Adsbøl',
       'Karina Lorentzen Dehnhardt',
       'Karina Lorentzen',
       'Karina Dehnhardt',
       'Karsten Hønge',
       'Karsten Lauritzen',
       'Kasper Roug',
       'Kasper Sand Kjær',
       'Kasper Sand',
       'Kasper Kjær',
       'Katarina Ammitzbøll',
       'Kathrine Olldag',
       'Katrine Robsøe',
       'Kenneth Mikkelsen',
       'Kim Valentin',
       'Kirsten Normann Andersen',
       'Kirsten Normann',
       'Kirsten Andersen',
       'Kristian Hegaard',
       'Kristian Jensen',
       'Kristian Pihl Lorentzen',
       'Kristian Pihl',
       'Kristian Lorentzen',
       'Kristian Thulesen Dahl',
       'Kristian Thulesen',
       'Kristian Dahl',
       'Kaare Dybvad Bek',
       'Kaare Dybvad',
       'Kaare Bek',
       'Lars Aslan Rasmussen',
       'Lars Aslan',
       'Lars Rasmussen',
       'Lars Boje Mathiesen',
       'Lars Boje',
       'Lars Mathiesen',
       'Lars Christian Lilleholt',
       'Lars Christian',
       'Lars Lilleholt',
       'Lars Løkke Rasmussen',
       'Lars Løkke',
       'Lea Wermelin',
       'Leif Lahn Jensen',
       'Leif Lahn',
       'Leif Jensen',
       'Lennart Damsbo-Andersen',
       'Lisbeth Bech-Nielsen',
       'Lise Bech',
       'Liselott Blixt',
       'Lotte Rod',
       'Louise Schack Elholm',
       'Louise Schack',
       'Louise Elholm',
       'Mads  Fuglede',
       'Magnus Heunicke',
       'Mai Mercado',
       'Mai Villadsen',
       'Malte Larsen',
       'Marcus Knuth',
       'Marianne Jelved',
       'Marie Bjerre',
       'Marie Krarup',
       'Marlene Ambo-Rasmussen',
       'Martin Geertsen',
       'Martin Lidegaard',
       'Mattias Tesfaye',
       'Merete Scheelsbeck',
       'Mette Abildgaard',
       'Mette Frederiksen',
       'Mette Gjerskov',
       'Mette Thiesen',
       'Mette Hjermind Dencker',
       'Mette Hjermind',
       'Mette Dencker',
       'Michael Aastrup Jensen',
       'Michael Aastrup',
       'Michael Jensen',
       'Mogens Jensen',
       'Mona Juul',
       'Morten Bødskov',
       'Morten Dahlin',
       'Morten Messerschmidt',
       'Morten Østergaard',
       'Naser Khader',
       'Nick Hækkerup',
       'Nicolai Wammen',
       'Niels Flemming Hansen',
       'Niels Flemming',
       'Niels Hansen',
       'Ole Birk Olesen',
       'Ole Birk',
       'Orla Hav',
       'Orla Østerby',
       'Peder Hvelplund',
       'Per Larsen',
       'Pernille Rosenkrantz-Theil',
       'Pernille Skipper',
       'Pernille Vermund',
       'Peter Hummelgaard',
       'Peter Juel-Jensen',
       'Peter Seier Christensen',
       'Peter Christensen',
       'Peter Seier',
       'Peter Skaarup',
       'Pia Kjærsgaard',
       'Pia Olsen Dyhr',
       'Pia Olsen',
       'Pia Dyhr',
       'Preben Bang Henriksen',
       'Preben Bang',
       'Preben Henriksen',
       'Rasmus Jarlov',
       'Rasmus Nordqvist',
       'Rasmus Prehn',
       'Rasmus Stoklund',
       'Rasmus Vestergaard',
       'Rasmus Helveg Petersen',
       'Rasmus Helveg',
       'Rasmus Petersen',
       'Rasmus Horn Langhoff',
       'Rasmus Horn',
       'Rasmus Langhoff',
       'René Christensen',
       'Rosa Lund',
       'Rune Lund',
       'Samira Nawa',
       'Signe Munk',
       'Sikandar Siddique',
       'Simon Kollerup',
       'Simon Emil Ammitzbøll-Bille',
       'Simon Ammitzbøll-Bille',
       'Sjúrður Skaale',
       'Sofie Carsten Nielsen',
       'Sofie Carsten',
       'Sofie Nielsen',
       'Sophie Løhde',
       'Stén Knuth',
       'Stinus Lindgreen',
       'Susan Kronborg',
       'Susanne Zimmer',
       'Søren Espersen',
       'Søren Søndergaard',
       'Søren Egge Rasmussen',
       'Søren Egge',
       'Søren Rasmussen',
       'Søren Pape Poulsen',
       'Søren Pape',
       'Søren Poulsen',
       'Tanja Larsson',
       'Theresa Berg Andersen',
       'Theresa Berg',
       'Theresa Andersen',
       'Thomas Danielsen',
       'Thomas Jensen',
       'Tommy Ahlers',
       'Torsten Gejl',
       'Torsten Schack Pedersen',
       'Torsten Schack',
       'Torsten Pedersen',
       'Trine Bramsen',
       'Trine Torp',
       'Troels Ravn',
       'Troels Lund Poulsen',
       'Troels Lund',
       'Troels Poulsen',
       'Uffe Elbæk',
       'Ulla Tørnæs',
       'Victoria Velasquez',
       'Zenia Stampe',
       'Aaja Chemnitz Larsen',
       'Aaja Chemnitz',
       'Aaja Larsen']

def mp_check(text, mps = MPS):
    '''
    Checks MP mentions in article.
    '''
    if any(mp in text for mp in mps):
        name_matches = list(compress(mps, [mp in text for mp in mps]))
    else:
        name_matches = []
    return(name_matches)